/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.GenericComboBoxModel;
import Classes.JtableVeiculosEntrada;
import Classes.JtableVeiculosSaida;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    JtableVeiculosEntrada veic = new JtableVeiculosEntrada();
    JtableVeiculosSaida veicSaid = new JtableVeiculosSaida();
    protected static int row;
    protected static String id;
    protected static String data_entrada;
    protected static String horario_entrada;
    protected static String placa;
    protected static String modelo;
    GenericComboBoxModel com = new GenericComboBoxModel();

    public TelaPrincipal() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jTableVeiculosEnt.setModel(veic);
        List<String> tabChange = new ArrayList<String>();
        tabChange.add("VeiculosEntrada");
        tabChange.add("VeiculosSaida");

        jComboBoxTabs.setModel(com);
        com.addAll(tabChange);
        jComboBoxTabs.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonExitVeic = new javax.swing.JButton();
        jButtonEditVeic = new javax.swing.JButton();
        jButtonCadVeic = new javax.swing.JButton();
        jComboBoxTabs = new javax.swing.JComboBox<>();
        jLabelTabela = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVeiculosEnt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonExitVeic.setText("Saída de Veículos");
        jButtonExitVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitVeicActionPerformed(evt);
            }
        });

        jButtonEditVeic.setText("Edição de Veículos");
        jButtonEditVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditVeicActionPerformed(evt);
            }
        });

        jButtonCadVeic.setText("Entrada de Veículos");
        jButtonCadVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadVeicActionPerformed(evt);
            }
        });

        jComboBoxTabs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VeiculosEntrada", "VeiculosSaida", " " }));
        jComboBoxTabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTabsActionPerformed(evt);
            }
        });

        jLabelTabela.setText("Tabela");

        jTableVeiculosEnt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Data_Entrada", "Horário_Entrada", "Placa", "Modelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeiculosEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculosEntMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVeiculosEnt);
        if (jTableVeiculosEnt.getColumnModel().getColumnCount() > 0) {
            jTableVeiculosEnt.getColumnModel().getColumn(0).setResizable(false);
            jTableVeiculosEnt.getColumnModel().getColumn(1).setResizable(false);
            jTableVeiculosEnt.getColumnModel().getColumn(2).setResizable(false);
            jTableVeiculosEnt.getColumnModel().getColumn(3).setResizable(false);
            jTableVeiculosEnt.getColumnModel().getColumn(4).setResizable(false);
        }

        jDesktopPane1.setLayer(jButtonExitVeic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonEditVeic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadVeic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBoxTabs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelTabela, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadVeic)
                .addGap(44, 44, 44)
                .addComponent(jButtonEditVeic)
                .addGap(31, 31, 31)
                .addComponent(jButtonExitVeic)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExitVeic)
                    .addComponent(jButtonEditVeic)
                    .addComponent(jButtonCadVeic)
                    .addComponent(jComboBoxTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadVeicActionPerformed
        // TODO add your handling code here:
        Tela_Formulario dialog = new Tela_Formulario(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

        if (!dialog.mov.getModelo().equals("") && !dialog.mov.getPlaca().equals("")) {
            dialog.movDAO.saveOrUpdate(dialog.mov);
            veic.addRow(dialog.mov);
        }


    }//GEN-LAST:event_jButtonCadVeicActionPerformed

    private void jButtonEditVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditVeicActionPerformed
        // TODO add your handling code here:
        if (id == null || jComboBoxTabs.getSelectedIndex() == 1) {
            JOptionPane.showMessageDialog(
                    null, "Seleciona uma linha da tabela de Veiculos Entrada", "Mensagem de Erro", JOptionPane.ERROR_MESSAGE);
        } else {

            Tela_EditFormulario dialog = new Tela_EditFormulario(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
            if (!dialog.mov.getModelo().isEmpty() || !dialog.mov.getPlaca().isEmpty()) {
                dialog.movDAO.UpdateEnt(dialog.mov);
                veic.setValueAt2(dialog.mov.getModelo(), row, 0);
                veic.setValueAt2(dialog.mov.getPlaca(), row, 1);
                id = null;
            }
        }
    }//GEN-LAST:event_jButtonEditVeicActionPerformed

    private void jTableVeiculosEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculosEntMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {

            Object obj = (veic.getValueAt(jTableVeiculosEnt.getSelectedRow(), 0));
            Object obj1 = (veic.getValueAt(jTableVeiculosEnt.getSelectedRow(), 1));
            Object obj2 = (veic.getValueAt(jTableVeiculosEnt.getSelectedRow(), 2));
            Object obj3 = (veic.getValueAt(jTableVeiculosEnt.getSelectedRow(), 3));
            Object obj4 = (veic.getValueAt(jTableVeiculosEnt.getSelectedRow(), 4));

            row = jTableVeiculosEnt.getSelectedRow();
            id = obj.toString();
            data_entrada = obj1.toString();
            horario_entrada = obj2.toString();
            placa = obj3.toString();
            modelo = obj4.toString();

        }
    }//GEN-LAST:event_jTableVeiculosEntMouseClicked

    private void jButtonExitVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitVeicActionPerformed
        // TODO add your handling code here:
        if (id == null || jComboBoxTabs.getSelectedIndex() == 1) {
            JOptionPane.showMessageDialog(
                    null, "Seleciona uma linha da tabela de Veiculos Entrada", "Mensagem de Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            Tela_Saida dialog = new Tela_Saida(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
            if (dialog.m.getValor_pago() != 0) {
                veic.removeRow(row);
                veicSaid.addRow(dialog.m);
                id = null;
            }

        }
    }//GEN-LAST:event_jButtonExitVeicActionPerformed

    private void jComboBoxTabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTabsActionPerformed
        // TODO add your handling code here:
        if (jComboBoxTabs.getSelectedIndex() == 0) {
            jTableVeiculosEnt.setModel(veic);
        }
        if (jComboBoxTabs.getSelectedIndex() == 1) {
            jTableVeiculosEnt.setModel(veicSaid);

        }
    }//GEN-LAST:event_jComboBoxTabsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadVeic;
    private javax.swing.JButton jButtonEditVeic;
    private javax.swing.JButton jButtonExitVeic;
    private javax.swing.JComboBox<String> jComboBoxTabs;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelTabela;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVeiculosEnt;
    // End of variables declaration//GEN-END:variables
}
